@Catalog.Api_HostAddress = http://localhost:5025

### Post Create Category
POST {{Catalog.Api_HostAddress}}/category/
Content-Type: application/json

{
  "title": "teste1",
  "owner": "string",
  "description": "string"
}

###
